# Generated by Django 4.1.2 on 2022-10-29 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogParser', '0002_alter_logfile_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogFileDetail',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('raw_number', models.CharField(default='', max_length=200)),
                ('creation_time', models.CharField(default='', max_length=200)),
                ('flagged', models.BooleanField(default=False)),
                ('log_owner_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ReadLogFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='logs/')),
            ],
        ),
        migrations.AlterField(
            model_name='logfile',
            name='owner',
            field=models.BooleanField(default='', max_length=200),
        ),
    ]
