# Generated by Django 4.1.2 on 2022-10-30 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LogParser', '0004_belonging'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogParserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='place_list', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='logfile',
            name='owner',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.DeleteModel(
            name='Belonging',
        ),
    ]
