# Generated by Django 4.1.2 on 2022-10-31 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LogParser', '0005_logparserpermission_alter_logfile_owner_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logfile',
            old_name='title',
            new_name='file_name',
        ),
    ]
