# Generated by Django 4.1.2 on 2022-10-31 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogParser', '0006_rename_title_logfile_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='logfile',
            name='creation_time',
            field=models.CharField(default='', max_length=200),
        ),
    ]
