# Generated by Django 4.1.2 on 2022-10-31 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LogParser', '0007_logfile_creation_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logfiledetail',
            old_name='log_owner_id',
            new_name='log_file_id',
        ),
    ]
