# Generated by Django 4.1.2 on 2022-10-31 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LogParser', '0008_rename_log_owner_id_logfiledetail_log_file_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logfile',
            old_name='creation_time',
            new_name='created_at',
        ),
    ]
