# Generated by Django 4.1.2 on 2022-10-31 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LogParser', '0009_rename_creation_time_logfile_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logfiledetail',
            old_name='creation_time',
            new_name='created_at',
        ),
    ]
