# Generated by Django 4.1.2 on 2022-10-31 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogParser', '0010_rename_creation_time_logfiledetail_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='logfiledetail',
            name='raw_text',
            field=models.CharField(default='', max_length=200),
        ),
    ]
