# Generated by Django 4.1.2 on 2022-10-31 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogParser', '0011_logfiledetail_raw_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logfile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
